In [ ]:
### Pandas is a Python library used for data manipulation and 
# analysis that provides high-level data structures like Series 
# and DataFrame to work with structured data efficiently.

In [ ]:
### Pandas helps you read, clean, manipulate, and 
# analyze data in table form (rows and columns).

In [ ]:
### NumPy → works with arrays
### Pandas → works with tables (like Excel / SQL)

In [ ]:
### pandas is used for two primary data structures
### -> series = one dimension like array object
### -> DataFrame = two dimension like array object

In [1]:
### Install pandas to use -> pip install pandas

!pip install pandas

Collecting pandas
  Downloading pandas-3.0.0-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rahul\onedrive\desktop\ai\ml\myvenv\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rahul\onedrive\desktop\ai\ml\myvenv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\rahul\onedrive\desktop\ai\ml\myvenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.7 MB 5.6 MB/s eta 0:00:02
   ----- ---------------------------------- 1.3/9.7 MB 3.5 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/9.7 MB 3.7 MB/s eta 0:00:02
   ----------- ---------------------------- 2.9/9.7 MB 3.5 MB/s eta 0:00:02
   --------------- ------------------------ 3.7/9.7 MB 3.6 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.7 MB 3.4 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.7 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.7 MB 3.4 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.7 MB 3.4 MB/s eta 0:00:02
   ---------------------------- ----------- 6.8/9.7 MB 3.3 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.7 MB 3.2 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.7 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 3.7 MB/s  0:00:02
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.0 tzdata-2025.3

In [ ]:
import pandas as pd

### lets study pandas series
### A pandas series i a one-dimensional array like object that can hold any data type

data = [1,2,3,4,5,6]

series = pd.Series(data)
print(series) ### default indexs are 0,1,2,3,4,5

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
### series from dictionary elemets
import pandas as pd
data = {
    'a' : 1,
    'b' : 2,
    'c' : 3
}

series_dic = pd.Series(data)

print(series_dic) ### Here indexs are key and the actual values are keyvales

### index = keys , values = series values

a    1
b    2
c    3
dtype: int64

In [6]:
import pandas as pd

### Here creating my own indexs

data = [10,20,30,40,50]

indexs = ['a','b','c','d','e'] ### Indexs should be same as values

pd.Series(data,index=indexs)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [9]:
### Now lets study data frames in pandas
### -> its two dimensional, mutable and potential

### create a dataframe from dic from list

### When you create a Pandas DataFrame from a dictionary:
### Dictionary keys → column names
### Dictionary values → column data 

import pandas as pd

data = {
    'name' : ['Rahul',"sushma","adhvay"],
    'age'  : [25,33,2],
    'city' : ['new-york','seattle','lynnwood']
}

dataFrame = pd.DataFrame(data)

print(dataFrame)
print(type(dataFrame))

     name  age      city
0   Rahul   25  new-york
1  sushma   33   seattle
2  adhvay    2  lynnwood
<class 'pandas.DataFrame'>

In [12]:
### create a dataframe form list of dic

import pandas as pd

data = [
    {'name' : 'Rahul', 'age' : 25 , 'city' : 'new-york'},
    {'name' : 'Sushma', 'age' : 33 , 'city' : 'seattle'},
    {'name' : 'Advay', 'age' : 2 , 'city' : 'lynnwood'}
]

pd.DataFrame(data)

     name  age      city
0   Rahul   25  new-york
1  Sushma   33   seattle
2   Advay    2  lynnwood

In [15]:
### Reading from a csv file

import pandas as pd

dataframe = pd.read_csv('employees.csv')

dataframe.head(5) ### gives the first 5 rows

dataframe.tail(5) ### gives the last 5 rows

,EmployeeID,Name,Department,Age,Salary,ExperienceYears,City,JoinDate
5,106,David,Finance,40.0,110000,15,Chicago,2015-05-18
6,107,Nina,IT,27.0,72000,3,San Francisco,2023-02-12
7,108,Tom,Marketing,29.0,55000,4,New York,2021-09-25
8,109,Linda,Marketing,33.0,62000,7,Boston,2019-04-14
9,110,Chris,IT,NaN,80000,6,Seattle,2020-07-30

In [21]:
### Now most important accessing data from this dataframe

### pick all the elements which respective to name

dataframe['Name']
print(type(dataframe['Name'])) ## this will be series as it is an one-dimension array

<class 'pandas.Series'>

In [33]:
### using loc operation

dataframe.loc[1] ### accessing the row with index label 1

EmployeeID                102
Name                     Alex
Department                 HR
Age                      30.0
Salary                  60000
ExperienceYears             5
City                 New York
JoinDate           2021-03-10
Name: 1, dtype: object

In [ ]:
dataframe.iloc[1] ### cares about physical position

EmployeeID                101
Name                    Rahul
Department                 IT
Age                      25.0
Salary                  70000
ExperienceYears             2
City                  Seattle
JoinDate           2023-06-15
Name: 0, dtype: object

In [39]:
### accessing a specific element
### use at

dataframe.at[1,"Name"]

'Alex'

In [40]:
### accessing a specific element with index
### use iat

dataframe.iat[2,2]

'Finance'

In [43]:
### Data manipulation with data frames
### now adding a new column

dataframe['is_alive'] = ['yes','yes','yes','yes','yes','yes','yes','yes','yes','yes']

In [44]:
dataframe

,EmployeeID,Name,Department,Age,Salary,ExperienceYears,City,JoinDate,is_alive
0,101,Rahul,IT,25.0,70000,2,Seattle,2023-06-15,yes
1,102,Alex,HR,30.0,60000,5,New York,2021-03-10,yes
2,103,Sara,Finance,28.0,65000,4,Chicago,2022-01-20,yes
3,104,John,IT,35.0,90000,10,Seattle,2018-08-05,yes
4,105,Emily,HR,NaN,58000,3,Boston,2022-11-01,yes
5,106,David,Finance,40.0,110000,15,Chicago,2015-05-18,yes
6,107,Nina,IT,27.0,72000,3,San Francisco,2023-02-12,yes
7,108,Tom,Marketing,29.0,55000,4,New York,2021-09-25,yes
8,109,Linda,Marketing,33.0,62000,7,Boston,2019-04-14,yes
9,110,Chris,IT,NaN,80000,6,Seattle,2020-07-30,yes

In [45]:
### add age + 1 to everyone

dataframe['Age'] = dataframe['Age']+1

In [46]:
dataframe

,EmployeeID,Name,Department,Age,Salary,ExperienceYears,City,JoinDate,is_alive
0,101,Rahul,IT,26.0,70000,2,Seattle,2023-06-15,yes
1,102,Alex,HR,31.0,60000,5,New York,2021-03-10,yes
2,103,Sara,Finance,29.0,65000,4,Chicago,2022-01-20,yes
3,104,John,IT,36.0,90000,10,Seattle,2018-08-05,yes
4,105,Emily,HR,NaN,58000,3,Boston,2022-11-01,yes
5,106,David,Finance,41.0,110000,15,Chicago,2015-05-18,yes
6,107,Nina,IT,28.0,72000,3,San Francisco,2023-02-12,yes
7,108,Tom,Marketing,30.0,55000,4,New York,2021-09-25,yes
8,109,Linda,Marketing,34.0,62000,7,Boston,2019-04-14,yes
9,110,Chris,IT,NaN,80000,6,Seattle,2020-07-30,yes

In [48]:
### To get statistical summary

dataframe.describe()

       EmployeeID        Age         Salary  ExperienceYears
count    10.00000   8.000000      10.000000         10.00000
mean    105.50000  31.875000   72200.000000          5.90000
std       3.02765   4.882549   17041.126723          3.95671
min     101.00000  26.000000   55000.000000          2.00000
25%     103.25000  28.750000   60500.000000          3.25000
50%     105.50000  30.500000   67500.000000          4.50000
75%     107.75000  34.500000   78000.000000          6.75000
max     110.00000  41.000000  110000.000000         15.00000